ex186a is

  f is
    say "perform exit:"
    exit 0
    say "** not reachable code **"

  myExit : Exit_Handler is
    exit(code i32) void is
      io.err.println "*** user defined exit handler diverting exit $code ***"
      exit.env.abort

  exit myExit ()->
    f
    say "** not reachable code **"

  say "continue even though exit was called..."
